#ifndef __UI_CONSTANTS_H_
#define __UI_CONSTANTS_H_

// #define A_MANUFACTURING_LINE_MAX 7

#define SCREEN_HEIGHT 1000
#define SCREEN_WIDTH 2000
#define MAX_X 750
#define SCREEN_MAX_Y (SCREEN_HEIGHT / 2)

#define MANUFACTURING_LINE_X_VALUE -1200
#define MANUFACTURING_LINE_HEGHIT 50

#define A_MANUFACTURING_LINE_WIDTH 400
#define B_MANUFACTURING_LINE_WIDTH 300
#define C_MANUFACTURING_LINE_WIDTH 200

#define MANUFACTURING_LINES_Y_GAP (SCREEN_HEIGHT / 8)

#define A1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (1 * MANUFACTURING_LINES_Y_GAP))
#define A2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (2 * MANUFACTURING_LINES_Y_GAP))
#define A3_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (3 * MANUFACTURING_LINES_Y_GAP))
#define B1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (4 * MANUFACTURING_LINES_Y_GAP))
#define B2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (5 * MANUFACTURING_LINES_Y_GAP))
#define C1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (6 * MANUFACTURING_LINES_Y_GAP))
#define C2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (7 * MANUFACTURING_LINES_Y_GAP))

#define PATCHING_X_VALUE (MANUFACTURING_LINE_X_VALUE + A_MANUFACTURING_LINE_WIDTH + 100)
#define PATCHING_WIDTH 50
#define PATCHING_HEIGHT 50

#define A_PATCHING_Y_VALUE 250
#define B_PATCHING_Y_VALUE 0
#define C_PATCHING_Y_VALUE -250

#define PRINTER_X_VALUE (PATCHING_X_VALUE + PATCHING_WIDTH + 100)
#define PRINTER_WIDTH 300
#define PRINTER_HEIGHT 50

#define PRINTER_Y_VALUE (0 - PRINTER_HEIGHT / 2)
#define PRINTER_ANIMATION_Y_VALUE 30
#define PRINTER_ANIMATION_X_VALUE (PRINTER_X_VALUE + PRINTER_WIDTH / 2)

#define CONTAINER_X_VALUE (PRINTER_X_VALUE + PRINTER_WIDTH + 100)
#define CONTAINER_WIDTH 200
#define CONTAINER_HEIGHT 100

#define A_CONTAINER_Y_VALUE A_PATCHING_Y_VALUE
#define B_CONTAINER_Y_VALUE B_PATCHING_Y_VALUE
#define C_CONTAINER_Y_VALUE C_PATCHING_Y_VALUE

#define STORAGE_X_VALUE (CONTAINER_X_VALUE + CONTAINER_WIDTH + 100)
#define STORAGE_WIDTH 200
#define STORAGE_HEIGHT 500

#define STORAGE_Y_VALUE 0 - STORAGE_HEIGHT / 2

#define TRUCK_ROAD_X_VALUE (MAX_X - 300)

#define TRUCK_PARKING_WIDTH 300
#define TRUCK_PARKING_HEIGHT 100

#define TRUCK_1_ROAD_Y_VALUE A_PATCHING_Y_VALUE
#define TRUCK_2_ROAD_Y_VALUE B_PATCHING_Y_VALUE
#define TRUCK_3_ROAD_Y_VALUE C_PATCHING_Y_VALUE

/// Previouse Project Stuff

#define ROLLING_CROSSS_X (MANUFACTURING_LINE_X_VALUE + A_MANUFACTURING_LINE_WIDTH + 50)
#define ROLLING_CROSSS_Y 200 // ROLLING_CROSSS_Y for gate 1 and -ROLLING_CROSSS_Y for gate 2
#define ROLLING_CROSS_SIZE 70.0f
#define ROLLING_CROSS_DEGREE_PER_FRAME 8

#define METAL_DETECTOR_X PRINTER_ANIMATION_X_VALUE
#define METAL_DETECTOR_SIZE 80.0f

#define TITLE_TEXT_Y 450

#define MANUFACTURING_TITLE_TEXT_X MANUFACTURING_LINE_X_VALUE
#define PATCHING_TITLE_TEXT_X PATCHING_X_VALUE - 20
#define PRINTING_TITLE_TEXT_X PRINTER_X_VALUE + PRINTER_WIDTH / 2 - 50
#define CONTAINER_TITLE_TEXT_X CONTAINER_X_VALUE
#define STORAGE_TITLE_TEXT_X STORAGE_X_VALUE
#define TRUCK_TITLE_TEXT_X TRUCK_ROAD_X_VALUE

#define TELLER_Rx_Y_VALUE 50
#define TELLER_Ix_Y_VALUE -50
#define TELLER_Bx_Y_VALUE -150

#define PADDING_BETWEEN_OBJECTS 35
#define STEP_SIZE 20
#define TRUCK_STEP_SIZE 5

#define MAX_SPEED_PER_FRAM 0.4
#define FPS 30

#define RIGHT_DIRECTION 1
#define LEFT_DIRECTION -1

#define TYPE_A_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        200, 0, 0          \
    }
#define TYPE_B_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        0, 200, 0          \
    }
#define TYPE_C_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        0, 0, 200          \
    }

#define TRUCK_CONTAINER_HEIGHT 80
#define TRUCK_CONTAINER_WIDTH 120
#define TRUCK_CABIN_HEIGHT 50
#define TRUCK_CABIN_WIDTH 40
#define TRUCK_CABIN_Y_OFFSET (TRUCK_CONTAINER_HEIGHT - TRUCK_CABIN_HEIGHT) / 2

#define PARKED_TRUCK_X TRUCK_ROAD_X_VALUE + 10

#define PARKED_TRUCK_X_DISTANCE 0
#define LEFT_TRUCK_X_DISTANCE 200

#define PARKED_TRUCK_1_Y A_PATCHING_Y_VALUE + 12
#define PARKED_TRUCK_2_Y B_PATCHING_Y_VALUE + 12
#define PARKED_TRUCK_3_Y C_PATCHING_Y_VALUE + 12

#endif
