#ifndef __UI_CONSTANTS_H_
#define __UI_CONSTANTS_H_

#define A_QUEUES_MAX_PEOPLE 120

#define QUEUE_A1_X_VALUE -1200
#define QUEUE_A1_Y_VALUE 50
#define QUEUE_A1_WIDTH 400
#define QUEUE_A1_HEIGHT 430

#define QUEUE_A2_X_VALUE -1200
#define QUEUE_A2_Y_VALUE -480
#define QUEUE_A2_WIDTH 400
#define QUEUE_A2_HEIGHT 430

#define QUEUE_B_X_VALUE (QUEUE_A1_X_VALUE + QUEUE_A1_WIDTH + 100)
#define QUEUE_B1_Y_VALUE 165
#define QUEUE_B2_Y_VALUE -235
#define QUEUE_B_WIDTH 300
#define QUEUE_B_HEIGHT 70

#define ROLLING_GATES_X (QUEUE_A1_X_VALUE + QUEUE_A1_WIDTH + 50)
#define ROLLING_GATES_Y 200 // ROLLING_GATES_Y for gate 1 and -ROLLING_GATES_Y for gate 2
#define ROLLING_GATE_SIZE 70.0f
#define ROLLING_GATE_DEGREE_PER_FRAME 7

#define METAL_DETECTOR_X (QUEUE_B_X_VALUE + QUEUE_B_WIDTH + 50)
#define METAL_DETECTOR_SIZE 80.0f

#define INNER_GROUPING_AREA_X_VALUE (METAL_DETECTOR_X + 50)
#define INNER_GROUPING_AREA_Y_VALUE -400
#define INNER_GROUPING_AREA_WIDTH 400
#define INNER_GROUPING_AREA_HEIGHT 800

#define TELLER_QUEUE_X_VALUE (INNER_GROUPING_AREA_X_VALUE + INNER_GROUPING_AREA_WIDTH + 50)
#define TELLER_QUEUE_WIDTH 200
#define TELLER_QUEUE_HEIGHT 50

#define TELLER_X_VALUE (TELLER_QUEUE_X_VALUE + TELLER_QUEUE_WIDTH + 50)
#define TELLER_WIDTH 30
#define TELLER_HEIGHT 30

#define TELLER_Tx_Y_VALUE 150
#define TELLER_Rx_Y_VALUE 50
#define TELLER_Ix_Y_VALUE -50
#define TELLER_Bx_Y_VALUE -150

#define TELLER_TEXT_X (TELLER_X_VALUE + TELLER_WIDTH + 50)

#define PADDING_BETWEEN_PEOPLE 35
#define STEP_SIZE 20

#define MAX_SPEED_PER_FRAM 0.3
#define FPS 30

#define RIGHT_DIRECTION 1
#define LEFT_DIRECTION -1

#endif
