#ifndef __UI_CONSTANTS_H_
#define __UI_CONSTANTS_H_

// #define A_MANUFACTURING_LINE_MAX 7

#define SCREEN_HEIGHT 1000
#define SCREEN_WIDTH 2000
#define SCREEN_MAX_Y (SCREEN_HEIGHT / 2)

#define MANUFACTURING_LINE_X_VALUE -1200
#define MANUFACTURING_LINE_HEGHIT 50

#define A_MANUFACTURING_LINE_WIDTH 400
#define B_MANUFACTURING_LINE_WIDTH 300
#define C_MANUFACTURING_LINE_WIDTH 200

#define MANUFACTURING_LINES_Y_GAP (SCREEN_HEIGHT / 8)

#define A1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (1 * MANUFACTURING_LINES_Y_GAP))
#define A2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (2 * MANUFACTURING_LINES_Y_GAP))
#define A3_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (3 * MANUFACTURING_LINES_Y_GAP))
#define B1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (4 * MANUFACTURING_LINES_Y_GAP))
#define B2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (5 * MANUFACTURING_LINES_Y_GAP))
#define C1_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (6 * MANUFACTURING_LINES_Y_GAP))
#define C2_MANUFACTURING_LINE_Y_VALUE (SCREEN_MAX_Y - (7 * MANUFACTURING_LINES_Y_GAP))

/// Previouse Project Stuff

#define QUEUE_B_X_VALUE (MANUFACTURING_LINE_X_VALUE + A_MANUFACTURING_LINE_WIDTH + 100)
#define QUEUE_B1_Y_VALUE 165
#define QUEUE_B2_Y_VALUE -235
#define QUEUE_B_WIDTH 300
#define QUEUE_B_HEIGHT 70

#define ROLLING_GATES_X (MANUFACTURING_LINE_X_VALUE + A_MANUFACTURING_LINE_WIDTH + 50)
#define ROLLING_GATES_Y 200 // ROLLING_GATES_Y for gate 1 and -ROLLING_GATES_Y for gate 2
#define ROLLING_GATE_SIZE 70.0f
#define ROLLING_GATE_DEGREE_PER_FRAME 7

#define METAL_DETECTOR_X (QUEUE_B_X_VALUE + QUEUE_B_WIDTH + 50)
#define METAL_DETECTOR_SIZE 80.0f

#define INNER_GROUPING_AREA_X_VALUE (METAL_DETECTOR_X + 50)
#define INNER_GROUPING_AREA_Y_VALUE -400
#define INNER_GROUPING_AREA_WIDTH 400
#define INNER_GROUPING_AREA_HEIGHT 800

#define TELLER_QUEUE_X_VALUE (INNER_GROUPING_AREA_X_VALUE + INNER_GROUPING_AREA_WIDTH + 50)
#define TELLER_QUEUE_WIDTH 200
#define TELLER_QUEUE_HEIGHT 50

#define TELLER_X_VALUE (TELLER_QUEUE_X_VALUE + TELLER_QUEUE_WIDTH + 50)
#define TELLER_WIDTH 30
#define TELLER_HEIGHT 30

#define TELLER_Tx_Y_VALUE 150
#define TELLER_Rx_Y_VALUE 50
#define TELLER_Ix_Y_VALUE -50
#define TELLER_Bx_Y_VALUE -150

#define TELLER_TEXT_X (TELLER_X_VALUE + TELLER_WIDTH + 50)

#define TELLER_Rx_Y_VALUE 50
#define TELLER_Ix_Y_VALUE -50
#define TELLER_Bx_Y_VALUE -150

#define PADDING_BETWEEN_OBJECTS 35
#define STEP_SIZE 20

#define MAX_SPEED_PER_FRAM 0.4
#define FPS 30

#define RIGHT_DIRECTION 1
#define LEFT_DIRECTION -1

#define TYPE_A_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        200, 0, 0          \
    }
#define TYPE_B_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        0, 200, 0          \
    }
#define TYPE_C_COLOR_RGB_V \
    (GLubyte[])            \
    {                      \
        0, 0, 200          \
    }

#endif
